name: deploy-financial-calc-library

on:
  push:
    branches: 
      - main

jobs:
  test:
    name: Run all tests for financial calculations code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root

      - name: Run tests
        run: poetry run pytest

  deploy:
    name: Upload the package to TestPyPI and PyPI
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install packaging tools
        run: |
          pip install poetry twine

      - name: Build package
        run: |
          rm -rf dist
          poetry build

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
          TWINE_USERNAME2: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD2: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload -r testpypi dist/*
          twine upload dist/*
